### ISSUE TITLE
Error during profile calcs when running onshore wind

### ISSUE THREAD

**Issue by mmowers** [NREL/reVX#41]
**Bug Description**
Run fails with error, see traceback.

**Full Traceback**
```
ERROR - 2020-02-18 22:20:17,205 [reeds_cli.py:415] : Error running ReEDS CLI
Traceback (most recent call last):
  File "/home/mmowers/reVX/reVX/reeds/reeds_cli.py", line 413, in <module>
    main(obj={})
  File "/home/mmowers/anaconda3/envs/revx/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/mmowers/anaconda3/envs/revx/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/mmowers/anaconda3/envs/revx/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mmowers/anaconda3/envs/revx/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mmowers/anaconda3/envs/revx/lib/python3.7/site-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/mmowers/anaconda3/envs/revx/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mmowers/anaconda3/envs/revx/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/mmowers/anaconda3/envs/revx/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mmowers/reVX/reVX/reeds/reeds_cli.py", line 251, in profiles
    hourly=True)
  File "/home/mmowers/reVX/reVX/reeds/reeds_profiles.py", line 272, in run
    rp._run_parallel(max_workers=max_workers)
  File "/home/mmowers/reV/reV/rep_profiles/rep_profiles.py", line 993, in _run_parallel
    profiles, _, ggids, rgids = future.result()
  File "/home/mmowers/anaconda3/envs/revx/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/mmowers/anaconda3/envs/revx/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```
**Additional**
See /scratch/mmowers/revx/logs/ and /scratch/mmowers/revx/output/ on Eagle.

**To Reproduce**
Use configuration from /scratch/mmowers/revx/testconfig.json

**System (please complete the following information):**
 - OS: Linux
 - Compute hardware: Eagle
 - Version: lastest master

**Comment by MRossol** [comment]
fixed in #43
