### ISSUE TITLE
reV-plexos

### ISSUE THREAD

**Issue by MRossol** [NREL/reVX#80]
**Bug Description**
Ilya and Mohit are trying to run the reV-plexos CLI (rev-reeds-plexos.py) and are getting the below error. Supposedly they were able to run this pipeline before (skeptical...)

**Full Traceback**
Traceback (most recent call last):
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/site-packages/reVX/plexos/rev_reeds_plexos.py", line 1011, in main
    forecast_fpath=pm.forecast_fpath, **agg_kwargs)
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/site-packages/reVX/plexos/rev_reeds_plexos.py", line 868, in run
    max_workers=max_workers)
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/site-packages/reVX/plexos/rev_reeds_plexos.py", line 347, in __init__
    self._sc_build = self._parse_rev_reeds(rev_sc, reeds_build)
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/site-packages/reVX/plexos/rev_reeds_plexos.py", line 585, in _parse_rev_reeds
    rev_sc, reeds_build, rev_join_on, reeds_join_on)
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/site-packages/reVX/plexos/rev_reeds_plexos.py", line 637, in _check_rev_reeds_coordinates
    rev_sc = rev_sc.sort_values(rev_join_on)
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/site-packages/pandas/core/frame.py", line 5452, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/site-packages/pandas/core/generic.py", line 1699, in _get_label_or_level_values
    f"The {label_axis_name} label '{key}' is not unique.{multi_message}"
ValueError: The column label 'sc_gid' is not unique.

**Code Sample**
running 

```python
reV-plexos CLI

```

**To Reproduce**
input file
[pv_sc.csv.zip](https://github.com/NREL/reVX/files/5889314/pv_sc.csv.zip)

**System (please complete the following information):**
 - Eagle, v0.3.15

**Additional context**
For Ilya and Mohit

**Charge code**
WFED.11320.01.01.03

**Comment by mohitjoshi1986** [comment]
I tried to remove sc_gid" from the supply curve files and just kept the "gid" column. Getting this error now
Traceback (most recent call last):
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/site-packages/reVX/plexos/rev_reeds_plexos.py", line 1011, in main
    forecast_fpath=pm.forecast_fpath, **agg_kwargs)
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/site-packages/reVX/plexos/rev_reeds_plexos.py", line 868, in run
    max_workers=max_workers)
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/site-packages/reVX/plexos/rev_reeds_plexos.py", line 347, in __init__
    self._sc_build = self._parse_rev_reeds(rev_sc, reeds_build)
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/site-packages/reVX/plexos/rev_reeds_plexos.py", line 585, in _parse_rev_reeds
    rev_sc, reeds_build, rev_join_on, reeds_join_on)
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/site-packages/reVX/plexos/rev_reeds_plexos.py", line 641, in _check_rev_reeds_coordinates
    atol=atol, rtol=0.0)
  File "<__array_function__ internals>", line 6, in allclose
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/site-packages/numpy/core/numeric.py", line 2189, in allclose
    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
  File "<__array_function__ internals>", line 6, in isclose
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/site-packages/numpy/core/numeric.py", line 2290, in isclose
    return within_tol(x, y, atol, rtol)
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/site-packages/numpy/core/numeric.py", line 2276, in within_tol
    return less_equal(abs(x-y), atol + rtol * abs(y))
ValueError: operands could not be broadcast together with shapes (24350,2) (0,2)

**Comment by mohitjoshi1986** [comment]
Different error while running the wind and rftp files separately (the last post was while running reVX for pv files).
ERROR - 2021-01-28 14:23:32,866 [rev_reeds_plexos.py:1014] : only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/site-packages/reVX/plexos/rev_reeds_plexos.py", line 297, in run
    profile, res_gids, gen_gids, res_built = n._make_node_profile()
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/site-packages/reVX/plexos/rev_reeds_plexos.py", line 249, in _make_node_profile
    self._build_sc_profile(i, profile)
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/site-packages/reVX/plexos/rev_reeds_plexos.py", line 206, in _build_sc_profile
    gen_gid = self._forecast_map[row['gen_gids']]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
"""

 

The above exception was the direct cause of the following exception:

 

Traceback (most recent call last):
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/site-packages/reVX/plexos/rev_reeds_plexos.py", line 1011, in main
    forecast_fpath=pm.forecast_fpath, **agg_kwargs)
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/site-packages/reVX/plexos/rev_reeds_plexos.py", line 869, in run
    profiles = pa._make_profiles()
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/site-packages/reVX/plexos/rev_reeds_plexos.py", line 756, in _make_profiles
    profiles = self._make_profiles_parallel()
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/site-packages/reVX/plexos/rev_reeds_plexos.py", line 788, in _make_profiles_parallel
    profile, res_gids, gen_gids, res_built = f.result()
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/site-packages/reVX/plexos/rev_reeds_plexos.py", line 297, in run
    profile, res_gids, gen_gids, res_built = n._make_node_profile()
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/site-packages/reVX/plexos/rev_reeds_plexos.py", line 249, in _make_node_profile
    self._build_sc_profile(i, profile)
  File "/home/mjoshi/.conda-envs/revx/lib/python3.7/site-packages/reVX/plexos/rev_reeds_plexos.py", line 206, in _build_sc_profile
    gen_gid = self._forecast_map[row['gen_gids']]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
